platform :ios, '10.0'

target 'CSChat' do
  use_frameworks!

  # 3rd party
  pod 'Alamofire'
  pod 'AlamofireObjectMapper'
  pod 'Kingfisher'
  pod 'GestureRecognizerClosures'
  pod 'BRYParseKeyboardNotification'

  # Public - Mirego
  pod 'MCUIColorUtils', :git => 'https://github.com/mirego/MCUIColorUtils.git'
  pod 'MCUIViewLayout', :git => 'https://github.com/mirego/MCUIViewLayout.git'
  pod 'MRGTaylor', :git => 'https://github.com/mirego/taylor-ios.git'
end
